### PR TITLE
Change OTLP/HTTP port (#389)

### PR DESCRIPTION
**Pull request by 0xRenegade**

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]

**Comment by SeanHood** [comment]
This PR changed the default port for OTLP/GRPC as well as OTLP/HTTP. I think only the latter was intended to be changed.

To add confusion to the mix, https://github.com/open-telemetry/opentelemetry-specification/pull/1847 the new OTLP/HTTP port change in the spec had been reverted as it may be possible after all.

**Comment by bobstrecansky** [comment]
Yeah, just saw that - we can revert this PR for now if that's cool with you @SeanHood .

**Comment by SeanHood** [comment]
I think that might be best for now

**Comment by bobstrecansky** [comment]
If you'll do me a huge favor and open the revert for this PR, I'll approve and merge it.

**Pull request merged**
