### PR TITLE
chore: fix broken link describing the usage of env vars for config

### PR DESCRIPTION
**Pull request by roman-kovalev**
I've noticed that one of the links in the repo is outdated. Here's a fix

### CODE REVIEW

**Comment by brettmc** [comment]
Thanks @roman-kovalev - you just need to sign the CLA so that I can merge this.

**Comment by roman-kovalev** [comment]
> Thanks @roman-kovalev - you just need to sign the CLA so that I can merge this.

@brettmc I did it few hours ago but still seeing this failed check 😕 Maybe you could kindly suggest what to do next with the signed PDF?

**Comment by roman-kovalev** [comment]
Opened [another one](https://github.com/open-telemetry/opentelemetry-php/pull/1122), hopefully it will fix the CLA issue

**Comment by brettmc** [comment]
> @brettmc I did it few hours ago but still seeing this failed check 😕 Maybe you could kindly suggest what to do next with the signed PDF?

signed PDF? Is this a company CLA? I thought it was all online (at least, that was my experience signing an individual CLA). If you've signed a physical document, it might be waiting for a human to process it, but I don't know anything about that. Resubmitting the same PR multiple times won't help though. I can force it to re-check the CLA from a PR, so please don't submit any new PRs for this.

**Comment by roman-kovalev** [comment]
> signed PDF? Is this a company CLA? 
No, not a physical doc, an individual via docusign. It is passed in another PR btw.
I think the problem with this one is that I accidentally pushed a commit using my work GH profile @roman-kovalev-aks that's why it messed up.
I'd suggest you to close this one and approve #1122 instead, all good there 🙂 
Thank you!

**Pull request closed without merging**
