### PR TITLE
Exporter Refactoring

### PR DESCRIPTION
**Pull request by tidal**
- Closes: https://github.com/open-telemetry/opentelemetry-php/issues/452
- Fixes 10) from https://github.com/open-telemetry/opentelemetry-php/issues/451
- Adds composer package dg/bypass-finals to allow mocking of final classes/methods

This is mainly a refactoring and abstraction of exporters and respective tests to make the code easier maintainable (removing most of the duplicate code) and a setup for comimg changes to the exporter factory etc. Besides allowing URLs without ports and/or paths, this PR doesn't change any behavior.

An example, how the ZipkinExporterTest looks like now:

```php
<?php

declare(strict_types=1);

namespace OpenTelemetry\Tests\Contrib\Unit;

use OpenTelemetry\Contrib\Zipkin\Exporter;

class ZipkinExporterTest extends AbstractHttpExporterTest
{
    protected const EXPORTER_NAME = 'test.zipkin';

    /**
     * @psalm-suppress PossiblyInvalidArgument
     */
    public function createExporterWithDsn(string $dsn): Exporter
    {
        return new Exporter(
            self::EXPORTER_NAME,
            $dsn,
            $this->getClientInterfaceMock(),
            $this->getRequestFactoryInterfaceMock(),
            $this->getStreamFactoryInterfaceMock()
        );
    }
}
```

### CODE REVIEW

**Comment by tidal** [comment]
The tests seem to fail, because the `assert` functions are not executed in CI.
I will quick fix this, and we can later investigate the reason.

**Comment by tidal** [comment]
The tests failed because the `assert` functions have not been excecuted in the CI run. I have temporarily fixed this by always throwing exceptions, so we can later find out how to make CI execute  `assert` (Its probably a production ini setting).

**Comment by tidal** [comment]
Please do not merge, yet. I want to add (or actually remove) some more things.

**Comment by tidal** [comment]
It's ok for me now. 
(However I had to resolve the merge conflits twice, because github was pulling in changes from other PRs into my dev branch. That's why there are all these duplicate commits).
The Psalm Code Scanning job seems to be stuck though.

**Review by bobstrecansky — APPROVED** [review]

**Pull request merged**
