### PR TITLE
Update PHP CS Fixer

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]
Thank you for the PR!  After your CLA is signed I'll merge this.

**Comment by keradus** [comment]
DocuSign crashed for me on first attempt.
On 2nd one, it allowed me to create 30days trial only.

maybe it's related to fact I'm using DocuSign at work for different account.

**Comment by bobstrecansky** [comment]
Yes more than likely.  I'm sorry that is frustrating.  Perhaps you have a personal account you can commit and sign with?

**Comment by keradus** [comment]
I am commiting on git with personal account and i DocuSign crashes for me.
I already spent more time with signing the CLA than raising the PR itself and kind-of not interested for figuring out how to force it to work for this few-liners PR.

please, consider merging as-is or closing the PR.

**Comment by bobstrecansky** [comment]
I'll close this one and reopen it myself so we can get it approved and merged.  Thank you for your contribution!

**Comment by bobstrecansky** [comment]
I've opened https://github.com/open-telemetry/opentelemetry-php/pull/243 to include this, and will merge when another approver approves the PR.

**Pull request closed without merging**
