### PR TITLE
Add: OTLP/HTTP JSON Exporter Support

### PR DESCRIPTION
**Pull request by riticksingh**

### CODE REVIEW

**Comment by prondubuisi** [comment]
Hello @riticksingh for EasyCLA I think you need to sign here https://contributor.lfcla.com/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/d5022c4b-1186-4037-a564-17de52c88e4f/individual

**Comment by bobstrecansky** [comment]
You'll need to sign the easyCLA at the link @prondubuisi added and fix the errors that come back from your PR's CI details here:

https://github.com/open-telemetry/opentelemetry-php/pull/202/checks?check_run_id=1332070835

**Comment by prondubuisi** [comment]
Also @bobstrecansky I am wondering why the fork for this PR is from [your Repo](https://github.com/bobstrecansky/opentelemetry-php) and not this one directly

**Comment by bobstrecansky** [comment]
@prondubuisi - I gave @riticksingh some example code to get started, it appears he used that fork directly for this as a base.

**Comment by prondubuisi** [comment]
> @prondubuisi - I gave @riticksingh some example code to get started, it appears he used that fork directly for this as a base.

Okay, looks good!

**Comment by bobstrecansky** [comment]
This PR needs more test coverage to be accepted.

**Comment by bobstrecansky** [comment]
There are test examples in the `test/sdk` directory.

**Comment by riticksingh** [comment]
Can't able to solve the easyCLA error, So closing this one and opening a new PR from my branch

**Pull request closed without merging**
