### PR TITLE
Workflow to publish phpdoc to github pages

### PR DESCRIPTION
**Pull request by svrnm**
Follow-up to #1378 and #1385:

I did some investigation how to best publish the API documentation for PHP. Initially I was hoping that we can serve these pages through netlify (the service we use to publish opentelemetry.io), unfrotunately I ran into some limitations in my experiment, that I could not resolve, see: https://github.com/open-telemetry/opentelemetry.io/pull/5413

Therefore I suggest to publish the pages to github via the workflow in this PR. This will create a page similar to

https://svrnm.github.io/opentelemetry-php/

(it will then be named https://open-telemetry.github.io/opentelemetry-php/)

We can then link this page from the website here: https://opentelemetry.io/docs/languages/#api-references and from within the navigation tree of the PHP language specific documentation.

Workflow run example:

https://github.com/svrnm/opentelemetry-php/actions/runs/11512969202/job/32048846572

cc @open-telemetry/docs-approvers

### CODE REVIEW

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
@svrnm merged. The workflow looks to have completed successfully, but I don't see any generated pages.... https://github.com/open-telemetry/opentelemetry-php/actions/runs/11543950343

**Comment by svrnm** [comment]
@brettmc have you enabled GitHub pages in the repo settings?

**Comment by brettmc** [comment]
Oh, I think I found it. Pages are configured to auto-generate:
Screenshot from 2024-10-29 10-10-46
I'll turn that off and see what happens...

**Comment by brettmc** [comment]
I also notice now that the new workflow file doesn't have an extension. I think .yaml or .yml extension is required?

**Comment by svrnm** [comment]
Thanks for investigating what the issue is!

> I also notice now that the new workflow file doesn't have an extension. I think .yaml or .yml extension is required?

Oh yes, my bad! The issue is that I had to test the workflow on the main branch of my fork so I copied and pasted the final version into a branch but forgot the .yml 🤦‍♂️

**Pull request merged**
