### PR TITLE
Built-in samplers implementation

### PR DESCRIPTION
**Pull request by lalex**
Added built-in samplers:
- AlwaysOffSampler
- AlwaysOnSampler
- AlwaysParentSampler
- ProbabilitySampler

Examples (from /examples dir) might be broken and should be reviewed.

`Sampler` instance could be a part of the `TracerProvider` settings.

### CODE REVIEW

**Comment by bobstrecansky** [comment]
I'm going to merge in our open PR, pull this and master, and validate!

**Comment by bobstrecansky** [comment]
@lalex - this PR looks like a great start!  We had some interface refactoring done in a PR recently.  I'd love to work with you to get this in that format!

If you'd like to chat more, feel free to join us in the opentelemetry-php channel:
https://gitter.im/open-telemetry/opentelemetry-php

**Comment by bobstrecansky** [comment]
This PR looks great!  I did notice that the examples were broken in this PR.  I think we need to:

1.  Fix the references for `OpenTelemetry\Sdk\Trace\Always[On|Off]Sampler in the examples directory
2.  Fix the `make examples` reference in the Makefile

Then I think this PR should be ready to ship!

**Comment by lalex** [comment]
@bobstrecansky Thank you for your comments!
I've made examples working again. But they do not store any records to Zipkin due to malformed timestamp format caused by `OpenTelemetry\Sdk\Internal\Clock`. I think that fix is out of this PR.

**Comment by morrisonlevi** [comment]
@lalex Hello! I opened a PR to bring it more in line with our style. I don't know if you didn't check the "allow edits from maintainer box", or if I'm not considered a maintainer, or I would have just pushed it directly.

**Pull request merged**
