### PR TITLE
split config into own package

### PR DESCRIPTION
**Pull request by brettmc**
Moving configuration code out of the SDK means that it can be used by components that should not depend on the SDK.
- move config into own package
- update all core components which were self-managing config to use the config package
- add some tests for config package to get coverage to 100%
- add missing type-hints to config package
- add missing config variables (OTEL_PHP_DEBUG_SCOPES_DISABLED and OTEL_PHP_FIBERS_ENABLED)

Prior to merge:
- [ ] create gitsplit target repo
- [ ] document that some components which formerly allowed truthy/falsey values will (or soon will) only accept `true` or `false`

Closes: #1245

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]

**Comment by Nevay** [comment]
IMO we shouldn't move everything out of the SDK, I would keep `Variables` (and `Defaults` + `KnownValues` if needed) in the component that uses them.

`Configuration::validateVariableType()` + `ValueTypes` + `VariableTypes` can be removed. They are only used to verify that code calls the correct method; no need to check this during runtime / should be verified by tests.

> Because all of our configuration-management code is in the SDK, it's not usable by contrib modules etc which need to deal with config

We should also take file configuration and configuration via code into account. The configuration formats do not match 1:1 -> an intermediate instrumentation configuration model would make sense instead of using `Configuration::getXXX()` directly. This would be especially useful for complex configuration options that cannot be expressed as environment variable, e.g. configuration for a SQL sanitizer.

Example: HTTP instrumentation needs to know which request and response headers should be recorded as attributes. Env/ini configuration currently uses `otel.instrumentation.http.request_headers` and `otel.instrumentation.http.response_headers`, while file configuration might use:
```yaml
instrumentation:
  config:
  - http_client:
      request_headers: []
      response_headers: []
```
Both formats could then populate the following intermediate model that is made available via a registry `InstrumentationConfigurationRegistry::get(HttpClientInstrumentation::class)`.
```php
class HttpClientInstrumentation implements InstrumentationConfiguration {
    public function __construct(
        public readonly array $requestHeaders = [],
        public readonly array $responseHeaders = [],
    ) {}
}
```

**Comment by brettmc** [comment]
@Nevay

> Configuration::validateVariableType() + ValueTypes + VariableTypes can be removed

Removed.

> IMO we shouldn't move everything out of the SDK, I would keep Variables (and Defaults + KnownValues if needed) in the component that uses them.

I'm hesitant to do this, because then contrib packages need to depend on SDK to fetch config (unless we start splitting config up into `SDK`, `general`, and possibly also for any packages that have custom config)?

> Both formats could then populate the following intermediate model that is made available via a registry

I started playing around with this. I thought perhaps factories could accept an `InstrumentationConfiguration`. It felt like double-handling if a ComponentProvider created an intermediate configuration, and as it stands the various factories build their own config as they go. Maybe this is worth a follow-up PR?

**Comment by Nevay** [comment]
> I'm hesitant to do this, because then contrib packages need to depend on SDK to fetch config (unless we start splitting config up into SDK, general, and possibly also for any packages that have custom config)?

`Variables` & co. contain only constants, not the code to actually fetch config.

> I started playing around with this. I thought perhaps factories could accept an InstrumentationConfiguration. It felt like double-handling if a ComponentProvider created an intermediate configuration, and as it stands the various factories build their own config as they go. Maybe this is worth a follow-up PR?

I've created a prototype that utilizes the idea of https://github.com/open-telemetry/opentelemetry-php/pull/1274 to inject configuration into instrumentation: https://github.com/Nevay/opentelemetry-php/commit/2ecf4b22c0c8d76f07d6238cd75c27167d396b15

**Comment by brettmc** [comment]
Closing, replaced by #1304

**Pull request closed without merging**
