### PR TITLE
rename make examples to make tracing examples

### LINKED ISSUE #191: Rename make command for tracing examples
# Problem
Make commands for tracing examples currently reads `make examples` as we scale and include more examples, this might become confusing

# Solution 
rename `make examples` to `make trace examples ` 

as recommended by @bobstrecansky [here](https://github.com/open-telemetry/opentelemetry-php/pull/188#pullrequestreview-497464422)

### PR DESCRIPTION
**Pull request by prondubuisi**
fixes #191

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]

**Comment by bobstrecansky** [comment]
This looks good, but you might also need to rename the value in the Makefile.

**Comment by prondubuisi** [comment]
Hello @bobstrecansky yes, remember I still have a `[PR](https://github.com/open-telemetry/opentelemetry-php/pull/188)` pending for the readme, will update that with all the changes made today once this is merged.

**Comment by bobstrecansky** [comment]
Yup!  You'll probably just want to update this line to `make trace examples`:
https://github.com/open-telemetry/opentelemetry-php/pull/188/files#diff-04c6e90faac2675aa89e2176d2eec7d8R66

**Comment by prondubuisi** [comment]
> Yup! You'll probably just want to update this line to `make trace examples`:
> https://github.com/open-telemetry/opentelemetry-php/pull/188/files#diff-04c6e90faac2675aa89e2176d2eec7d8R66

Updated, thanks!

**Pull request merged**
