### PR TITLE
Fixing Style from PR

### PR DESCRIPTION
**Pull request by bobstrecansky**
@wRLSS 's [PR](https://github.com/open-telemetry/opentelemetry-php/pull/248) had a slight style error, but it was not caught in CI because we were waiting for the [github master / main action PR](https://github.com/open-telemetry/opentelemetry-php/pull/245) to be fixed.  This PR fixes up the one styling error that came about so that the CI passes.

### CODE REVIEW

**Comment by bobstrecansky** [comment]
@wRLSS - I was looking through this, and I noticed phan errored out as well.  the version number is an optional parameter, and that gives you a collision with sprintf.   I'm happy to change this as well if you'd like - should we make a conditional based on the presence of `version` here?  Open to other thoughts as well.

**Comment by wRLSS** [comment]
That's actually weird, I just double-checked this via phpstan and the statement is evaluated correctly. 
https://phpstan.org/r/126dc1c4-e97c-4a6b-9107-1dcf89c148fa

Anyways,  I guess we can change `if` part to null coalesce, a bit simpler
`sprintf("%s@%s", $name, ($version ?? 'unknown'));`

**Review by Fahmy-Mohammed — APPROVED** [review]

**Comment by bobstrecansky** [comment]
Updated.  The null coalescing operator made sense to me - it looked less readable at the beginning, but ✅

**Comment by bobstrecansky** [comment]
@morrisonlevi @beniamin for review please.

**Review by beniamin — APPROVED** [review]

**Pull request merged**
