### PR TITLE
fixing otlp span converter with ext-protobuf

### LINKED ISSUE #357: OTLP/GRPC exporter implementation - `Cannot convert '' to string` exception on empty `parent_span_id` with ext-protobuf
**Environment** 
docker image: `php:7.4.20-fpm-alpine`
related php-ext enabled: `grpc-1.38.0`, `protobuf-3.17.3`
library: `open-telemetry/opentelemetry: 0.0.2`,
jaeger metrics collector: `jaegertracing/opentelemetry-all-in-one`

**Steps to reproduce**
```php

use OpenTelemetry\Contrib\OtlpGrpc\Exporter;
use OpenTelemetry\Sdk\Resource\ResourceInfo;
use OpenTelemetry\Sdk\Trace\Clock;
use OpenTelemetry\Sdk\Trace\Sampler\AlwaysOnSampler;
use OpenTelemetry\Sdk\Trace\SpanProcessor\BatchSpanProcessor;
use OpenTelemetry\Sdk\Trace\TracerProvider;
use OpenTelemetry\Trace\SpanKind;
use OpenTelemetry\Trace\SpanStatus;

$exporter = new Exporter('home.docker.internal:55680'); // point to jaegertracing/opentelemetry-all-in-one

$tracer =  (new TracerProvider(
    ResourceInfo::defaultResource(),
    new AlwaysOnSampler())
)->addSpanProcessor(new BatchSpanProcessor($exporter, Clock::get()))->getTracer('tracername', 'doesntmatter');

$span = $tracer->startAndActivateSpan($request->getMethod(), SpanKind::KIND_SERVER);

if ($span->isRecording()) {
    $span->setAttribute('attribute1', 'value1');
}

$span->setSpanStatus(SpanStatus::OK);
$tracer->endActiveSpan();

// To easily catch exception make `\OpenTelemetry\Sdk\Trace\Tracer::$provider` public
$tracer->provider->shutdown();
```

**What is the expected behavior?**
Tracing information appears in jaeger

**What is the actual behavior?**
Exception: **Cannot convert '' to string**
```
Google\Protobuf\Internal\Message::__construct
vendor/open-telemetry/opentelemetry/proto/Opentelemetry/Proto/Trace/V1/Span.php:244
```

**Additional context**
This exception does not appear in next cases (independently of each other):

- Using `google/protobuf` instead of `ext-protobuf`
- Using non-empty `parentId` in context as well as using invalid `parentId` as parent one 
```php
- 'parent_span_id' => $parent_span_id ? hex2bin($parent_span_id) : null,
+ 'parent_span_id' => $parent_span_id ? hex2bin($parent_span_id) : hex2bin(\OpenTelemetry\Sdk\Trace\SpanContext::INVALID_SPAN),
```
during row initialisation in `vendor/open-telemetry/opentelemetry/contrib/OtlpGrpc/SpanConverter.php:91`.

**NB!** This issue can be related to the protobuf extension, not opentelemetry package

### PR DESCRIPTION
**Pull request by brettmc**
There looks to be a bug in ext-protobuf (but not the protobuf php library), where an array with any empty string top-level values cause an error. A workaround for this is to strip out entries with empty values.
Adding ext-protobuf to the test matrix, and in passing fixing a mis-named test class.
Closes #357

### CODE REVIEW

**Comment by brettmc** [comment]
It looks like ext-protobuf + 8.1 is going to be broken for a little while yet... Evidently phpunit is ok with deprecation notices from the library but not the extension (I think it's because the extension is loaded on php startup).
I have a PR in-flight to fix those deprecations in the extension.

**Review by bobstrecansky — APPROVED** [review]

**Comment by bobstrecansky** [comment]
Looks like some 8.1 test failures, but once those are resolved good to go

**Comment by brettmc** [comment]
@bobstrecansky - the failing 8.1 test is when the protobuf extension is installed. I've just added that to the test matrix, it would have failed before for 7.4 + 8.0 + 8.1, but now only fails for 8.1. It's progress, and is being tracked in #516

**Comment by tidal** [comment]
@brettmc 
Can you please add `ext-protobuf` as `suggest` to the composer.json files and in the README?

**Pull request merged**
