### PR TITLE
Otlp centralised config

### PR DESCRIPTION
**Pull request by brettmc**
This is stage 1 of implementing #383 - taking SeanHood's initial work and expanding on it to centralise the configuration of http and grpc flavours of otlp protocol:
* move all parameters from constructors of each exporter into ConfigOpts, and make that the only parameter to each exporter
* also move exporter-based environment variable config into ConfigOpts
* adjust "insecure" and "compression" header defaults to align to specification
* update all factories and tests which interact with these exporters to use ConfigOpts

Next steps:
* combine SpanConverters (they are almost identical)
* try to combine the Exporters

### CODE REVIEW

**Comment by tidal** [comment]
I'm sorry, this PR adds one more issue to https://github.com/open-telemetry/opentelemetry-php/issues/464, while I'm working on solving the remainig issues. There is sadly  is no simple solution, that's why it has taken a while. 

This will also break the Symfony SDKBundle. Breaking the Bundle is not the real issue, but it's breaking it in a way that is hard to fix, since the Config object creates more drift between the different exporters. 

It also makes my work on the exporter factory (including HTTP Client) more difficult. That's why [I had asked Sean](https://github.com/open-telemetry/opentelemetry-php/issues/464), if he is still working on the  options implementation. And that has been the reason for doing the [refactoring](https://github.com/open-telemetry/opentelemetry-php/pull/476) to get closer to having a streamlined approach for all exporters, while introducing a config object only for the Otlp exporters does the opposite. 

The different exporters have different configuration requirements, which additionally may belong to different logical layers/responsibilities (serialization, encryption, compression, transport, authentification, etc.), so one config class to rule them all would be no solution either. However, creating abstractions for the different layers/responsibilities and making those configurable could be.

**Comment by brettmc** [comment]
Thanks @tidal  - I'll park this for a couple of days and try to think through it a bit more. It seemed like a logical way to move towards merging the two OTLP exporters into one and getting rid all of the existing duplication, but I don't want to clobber your efforts!

**Comment by tidal** [comment]
@brettmc 
Thank you, too!!!


> It seemed like a logical way to move towards merging the two OTLP exporters into one and getting rid all of the existing duplication

Yes, I totally agree! However there should be a unified way to instantiate all exporters, especially for the use in  downstream packages/projects. I have been thinking about this for a while now, and tried a few things. I will try create a PR in the next days, and then we can have a look how can intergrate with moving the OTLP exporters into one. 

Anyway, the SpanConverters  are nor really touched by that, so you can still work on them, if you like. Maybe you have seen, that I introduced a [SpanConverterInterface](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/SpanConverterInterface.php) for all the other converters, but it could not be used for the OTLP converters, since there is no "convert" method like in the other converters. If you could make that happen, that would be awesome!!!

Maybe at the end we could have just one single exporter, which uses composition to get configured with different converters, transports and so on and the factory or a builder will take care of plugging all the things together? In that way we could also reduce dupilcation of zipkin, newrelic, zipkin+newrelic and whatever there may be be in the future.

**Review by bobstrecansky — APPROVED** [review]

**Comment by brettmc** [comment]
resurrecting for further discussion, but not ready to be merged yet.

**Pull request merged**
