### PR TITLE
Allow decoration of zipkin span converter

### PR DESCRIPTION
**Pull request by cdaguerre**

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]

**Review by brettmc — APPROVED** [review]

**Comment by bobstrecansky** [comment]
@cdaguerre - I think there are just some phan fixes necessary in the CI and then I believe we'll be good to go here!

**Comment by bobstrecansky** [comment]
Oh looks like this was fixed!

**Comment by brettmc** [comment]
Those phan issues are fixed upstream now, so just merging upstream/main into your branch should make everything green

**Comment by bobstrecansky** [comment]
@cdaguerre - would you like to make those PHP stan annotation fixes so we can merge this PR?

**Pull request merged**
