### PR TITLE
Allow for 'google/protobuf' '^4.0' to be used as well.

### LINKED ISSUE #1359: Introduce support for `google/protobuf` `^4.x`
Due to the current version constraints it's not possible for us to upgrade to `google/protobuf` `^4.x`, it be good to open up this upgrade path as not supporting it might lock people into older versions of other dependencies.

### PR DESCRIPTION
**Pull request by ldebrouwer**
Resolves #1359.

### CODE REVIEW

**Comment by brettmc** [comment]
The tests pass, but I think it's misleading. Because ext-protobuf is installed (at whatever version is "latest" according to PECL), that takes priority over any native version installed via composer.
Locally, if I install protobuf v4.27.3 and disable ext-protobuf, I see one test failure:
```
1) OpenTelemetry\Tests\Unit\Contrib\Otlp\SpanConverterTest::test_otlp_happy_path_span
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
                             'span_id' => '00000001'
                             'trace_state' => ''
                             'parent_span_id' => ''
-                            'flags' => 0
+                            'flags' => 256
                             'name' => 'http_get'
                             'kind' => 1
                             'start_time_unix_nano' => 1617313804325769988
```

**Comment by ldebrouwer** [comment]
@brettmc I'll have a look. May I ask how you're disabling `ext-protobuf`?

**Comment by brettmc** [comment]
using the docker image referenced from opentelemetry-php's Makefile, I just commented out the entry from `$(php-config --ini-dir)/docker-php-ext-protobuf.ini`. You could also remove it from `docker/Dockerfile` and build the image from scratch without ext-protobuf - it will be easier to `composer update` to switch between v3 and v4, I reckon.

**Comment by ldebrouwer** [comment]
I've had a look, but I get the _exact_ same test failure for `google/protobuf` on version `3.22.0` when `ext-protobuf` is not part of the image. The results between `4.27.3` and `3.22.0` for are the same, and `OpenTelemetry\Tests\Unit\Contrib\Otlp\SpanConverterTest::test_otlp_happy_path_span` only passes when `ext-protobuf` is installed and enabled.

**Comment by brettmc** [comment]
> Could you please advise on the preferred course of action?

Very interesting, so it seems that there is a small difference b/w native and ext. We strongly recommend folks to use the extension, so I'm not very worried about this.

Can you run the tests against ext-protobuf v4 and report back? If that's green, I'm happy to merge this and then create a follow-up issue to make sure our CI runs tests against both protobuf 3&4.

**Comment by ldebrouwer** [comment]
> Can you run the tests against ext-protobuf v4 and report back?

The tests are already running against `ext-protobuf` `^4.x` because the version wasn't pinned in the Docker image.

<details>

<summary>Output for `ext-protobuf` version `4.27.3`</summary>

```
docker compose run --rm php bash
ce7cb87bfce4:/usr/src/myapp$ php --re protobuf | head -1
Extension [ <persistent> extension #38 protobuf version 4.27.3 ] {
ce7cb87bfce4:/usr/src/myapp$
exit
~/dev/opentelemetry-php   ProtoBuf4Support ●  make test
docker compose run --rm php env XDEBUG_MODE=coverage vendor/bin/phpunit --testsuite unit --colors=always
PHPUnit 10.1.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.29
Configuration: /usr/src/myapp/phpunit.xml.dist
Random Seed:   1723790325

.................................D...........................   61 / 1589 (  3%)
.............................................................  122 / 1589 (  7%)
.............................................................  183 / 1589 ( 11%)
.............................................................  244 / 1589 ( 15%)
.............................................................  305 / 1589 ( 19%)
.............................................................  366 / 1589 ( 23%)
.............................................................  427 / 1589 ( 26%)
.............................................................  488 / 1589 ( 30%)
.............................................................  549 / 1589 ( 34%)
.............................................................  610 / 1589 ( 38%)
......................S......................................  671 / 1589 ( 42%)
.............................................................  732 / 1589 ( 46%)
.............................................................  793 / 1589 ( 49%)
.............................................................  854 / 1589 ( 53%)
.............................................................  915 / 1589 ( 57%)
............................D................................  976 / 1589 ( 61%)
............................................................. 1037 / 1589 ( 65%)
............................................................. 1098 / 1589 ( 69%)
............................................................. 1159 / 1589 ( 72%)
............................................................. 1220 / 1589 ( 76%)
............................................................. 1281 / 1589 ( 80%)
............................................................. 1342 / 1589 ( 84%)
............................................................. 1403 / 1589 ( 88%)
............................................................. 1464 / 1589 ( 92%)
............................................................. 1525 / 1589 ( 95%)
............................................................. 1586 / 1589 ( 99%)
...                                                           1589 / 1589 (100%)

Time: 00:03.558, Memory: 78.00 MB

OK, but there are issues!
Tests: 1589, Assertions: 2579, Deprecations: 2, Skipped: 1.
docker compose run --rm php env XDEBUG_MODE=off vendor/bin/phpunit --testsuite integration --colors=always
PHPUnit 10.1.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.29
Configuration: /usr/src/myapp/phpunit.xml.dist
Random Seed:   1723790329

..................................S.............................. 65 / 92 ( 70%)
................S..........                                       92 / 92 (100%)

Time: 00:00.423, Memory: 20.00 MB

OK, but some tests were skipped!
Tests: 92, Assertions: 286, Skipped: 2.
```
</details>


<details>

<summary>Output for `ext-protobuf` version `3.25.4`</summary>

```
docker compose run --rm php-protobuf3 bash
f02299d4cdfe:/usr/src/myapp$ php --re protobuf | head -1
Extension [ <persistent> extension #38 protobuf version 3.25.4 ] {
f02299d4cdfe:/usr/src/myapp$
exit
~/dev/opentelemetry-php   ProtoBuf4Support ●  make test
docker compose run --rm php-sans-protobuf env XDEBUG_MODE=coverage vendor/bin/phpunit --testsuite unit --colors=always
PHPUnit 10.1.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.29
Configuration: /usr/src/myapp/phpunit.xml.dist
Random Seed:   1723791223

.............................................................   61 / 1589 (  3%)
.............................................................  122 / 1589 (  7%)
.........................D...................................  183 / 1589 ( 11%)
.............................................................  244 / 1589 ( 15%)
.............................................................  305 / 1589 ( 19%)
.............................................................  366 / 1589 ( 23%)
.....................................S.......................  427 / 1589 ( 26%)
.............................................................  488 / 1589 ( 30%)
.............................................................  549 / 1589 ( 34%)
.............................................................  610 / 1589 ( 38%)
.............................................................  671 / 1589 ( 42%)
.............................................................  732 / 1589 ( 46%)
.............................................................  793 / 1589 ( 49%)
.............................................................  854 / 1589 ( 53%)
.............................................................  915 / 1589 ( 57%)
.............................................................  976 / 1589 ( 61%)
............................................................. 1037 / 1589 ( 65%)
............................................................. 1098 / 1589 ( 69%)
..................................................D.......... 1159 / 1589 ( 72%)
............................................................. 1220 / 1589 ( 76%)
............................................................. 1281 / 1589 ( 80%)
............................................................. 1342 / 1589 ( 84%)
............................................................. 1403 / 1589 ( 88%)
............................................................. 1464 / 1589 ( 92%)
............................................................. 1525 / 1589 ( 95%)
............................................................. 1586 / 1589 ( 99%)
...                                                           1589 / 1589 (100%)

Time: 00:03.732, Memory: 88.00 MB

OK, but there are issues!
Tests: 1589, Assertions: 2580, Deprecations: 2, Skipped: 1.
docker compose run --rm php-sans-protobuf env XDEBUG_MODE=off vendor/bin/phpunit --testsuite integration --colors=always
PHPUnit 10.1.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.29
Configuration: /usr/src/myapp/phpunit.xml.dist
Random Seed:   1723791228

S......................................S......................... 65 / 92 ( 70%)
...........................                                       92 / 92 (100%)

Time: 00:00.370, Memory: 20.00 MB

OK, but some tests were skipped!
Tests: 92, Assertions: 286, Skipped: 2.
```
</details>

So the results for `ext-protobuf` `3.x` and `4.x` are identical, and the results for `google/protobuf` `3.x` and `4.x` (without `ext-protobuf` being present) are identical. Which seems to corroborate that the we're looking at a difference between native and extension.

**Review by brettmc — APPROVED** [review]

**Pull request merged**
