### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by 94noni**

### CODE REVIEW

**Review by beniamin — APPROVED** [review]

**Comment by prondubuisi** [comment]
Hello @94noni good work spotting this, you need to get the CLA signed so this can be merged. You can do that here 
https://contributor.v1.easycla.lfx.linuxfoundation.org/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/d5022c4b-1186-4037-a564-17de52c88e4f

**Review by Fahmy-Mohammed — APPROVED** [review]

**Review by zsistla — APPROVED** [review]

**Comment by bobstrecansky** [comment]
@94noni - once you sign the CLA, we'll merge this PR!

**Comment by 94noni** [comment]
Hey :)
yes I will do it for sure
I am just afk for some days rn, perhaps you can cherry pick and merge otherwise
Cheers

**Comment by bobstrecansky** [comment]
Opened https://github.com/open-telemetry/opentelemetry-php/pull/320, will close this.

**Pull request closed without merging**
