### PR TITLE
Sampling spike

### PR DESCRIPTION
**Pull request by bobstrecansky**
This Spike has a bunch of new additions.  I used @nekufa's implementation as a base, and I added: 

- Vendored files and composer updates
- An examples directory with an example implementation, complete with a docker implementation.  
- An `AlwaysSample` and a `NeverSample` reference implementation.
- Updates to the README.md

You can use `./resources/example-using-docker` to give test out the example docker implementation.
You can use `./resources/test-using-docker` from the root directory of the repository to run all of the integration and unit tests in our repository.

### CODE REVIEW

**Comment by coudenysj** [comment]
@bobstrecansky Is it possible to add the `vendor` folder in the `.gitignore` file?

**Comment by bobstrecansky** [comment]
@coudenysj - I was vendoring in dependencies purposefully.  I think this is certainly something we should talk about as a group in our next meeting.

**Comment by coudenysj** [comment]
Yeah, sorry. Didn't mean to be rude :). Just had a hard time looking at the actual code because of all the changes.

**Comment by bobstrecansky** [comment]
You weren't being rude at all!  I'm going to refactor this after we merge the work we did today: https://github.com/open-telemetry/opentelemetry-php/pull/23

**Comment by bobstrecansky** [comment]
Closing this in favour of https://github.com/open-telemetry/opentelemetry-php/pull/30
@coudenysj - I think that should be a little clearer / more concise.

**Pull request closed without merging**
