### PR TITLE
Rename phpdoc-to-github-pages to phpdoc-to-github-pages.yml

### PR DESCRIPTION
**Pull request by svrnm**
follow up to #1418, where I named the file without the required YML suffix

### CODE REVIEW

**Comment by bobstrecansky** [comment]
@svrnm - anything else you want us to do with this PR?  Just merge?

**Comment by svrnm** [comment]
> @svrnm - anything else you want us to do with this PR? Just merge?

If that would be possible, yes. Testing github workflows is a nightmare. I also disabled it for pull requests since the goal should be a publication on commit to main

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
That's worked: https://open-telemetry.github.io/opentelemetry-php/

**Comment by svrnm** [comment]
thanks, let me add it to the website then :-)

**Pull request merged**
