### PR TITLE
Add an UpDownSumObserver Instrument for the Metrics API

### PR DESCRIPTION
**Pull request by tanweeralii**
#120

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]
Looks like a good start to me.  Are you planning on also implementing the SDK portion of this as well?

**Comment by prondubuisi** [comment]
Hello @tanweeralii good one, maybe we can add a test for this in the next PR

**Comment by tanweeralii** [comment]
> Looks like a good start to me. Are you planning on also implementing the SDK portion of this as well?

Yeah, I am planning to learn and surely I will work on that.

**Comment by tanweeralii** [comment]
> Hello @tanweeralii good one, maybe we can add a test for this in the next PR

Sure @prondubuisi

**Review by bobstrecansky — APPROVED** [review]

**Pull request merged**
