### PR TITLE
php-cs-fixer bugfix

### PR DESCRIPTION
**Pull request by bobstrecansky**
FIxes https://github.com/open-telemetry/opentelemetry-php/issues/212

This PR fixes the operation of php-cs-fixer in CI.  It was noted that php-cs-fixer wasn't running properly after the swap to Github actions, it was because of a `$TRAVIS_COMMIT_RANGE` variable that was left in the phpcs.sh script.  I determined we don't actually need that file, so I simplified the action to execute the php-cs-fixer directly.  There are 3 commits in this PR:

1) The fix: [bd6b845](https://github.com/open-telemetry/opentelemetry-php/pull/216/commits/bd6b845db22cb91b1458c367f7e0436db1fded54)

2) A purposeful failure: [8f6777b](https://github.com/open-telemetry/opentelemetry-php/pull/216/commits/8f6777b48ad9eb7138f202c8c6827cf53bc2f4a0) (In hindsight, I should have added additional failures here, happy to do so if requested)

3) A purposeful fix of that failure: [2e11a41](https://github.com/open-telemetry/opentelemetry-php/pull/216/commits/2e11a41256875f26dbbe706beaf8c805bbbb98c0) using `make style` locally.

Happy to answer any questions about this PR.

We also discussed potentially doing this as a git pre-commit check as well.  We still could, we would just need to ensure that the vendored binaries are installed (the php-cs-fixer runs from the vendored directory).

### CODE REVIEW

**Comment by bobstrecansky** [comment]
Also tagging @nenad as he did the initial implementation.

**Comment by bobstrecansky** [comment]
@morrisonlevi @beniamin for review please.

**Review by morrisonlevi — APPROVED** [review]
Looks good as far as I know; basically it checks all files instead of just committed ones?

**Comment by bobstrecansky** [comment]
@morrisonlevi - correct.  There isn't a `TRAVIS_COMMIT_RANGE` equivalent in Github Actions yet, so we have to check them all.  I think this is okay though - this process isn't very expensive and it follows the pattern that `make style` does locally.  Happy to change it if you'd rather something else.

**Comment by morrisonlevi** [comment]
It's fine; was just making sure I understood it correctly.

**Pull request merged**
