### PR TITLE
bugfix incorrect used class in laravel document implamentation

### PR DESCRIPTION
**Pull request by sajjadgol**

### CODE REVIEW

**Comment by tidal** [comment]
Thank you for contributing to opentelemetry-php.
Since we are a [CNCF](https://www.cncf.io/) project, we need contributers to sign a Contributor License Agreement ([see above](https://github.com/open-telemetry/opentelemetry-php/pull/543#issuecomment-1007227869))

However, I do not really understand, what kind of bug this PR is trying to fix.
The spelling of `SDK` in all uppercase letters is correct. See: [https://github.com/open-telemetry/opentelemetry-php/tree/main/src/SDK](https://github.com/open-telemetry/opentelemetry-php/tree/86ed4cff87fbe9cb2627aafcef810c4877c6c8ea/src/SDK)

**Comment by sajjadgol** [comment]
in version 0.0.2 document invalid

**Comment by tidal** [comment]
The document used the same spelling as the code was in v0.0.2.
Please take a look here: https://github.com/open-telemetry/opentelemetry-php/blob/0.0.2/docs/laravel-integration.md

However. our current version is 0.0.4. Please, upgrade to use this version.

On a personal note: Please, do not use the methods used in the Laravel or Symfony tutorials in production!

**Comment by bobstrecansky** [comment]
Yes, we feel as if this is correct in `main` - can you double check your installed version?

**Comment by bobstrecansky** [comment]
Going to close this for 7 days with no activity.

**Pull request closed without merging**
