### PR TITLE
change instances of probabilitysampler to traceidratiobasedsampler

### LINKED ISSUE #174: Naming Updates
To follow the spec, we should apply naming updates that were added to the specification:

Spec updates to apply for each language:
HTTPText propagator renamed to TextMap propagator (https://github.com/open-telemetry/opentelemetry-specification/pull/793)
ProbabilitySampler renamed to TraceIdRatioBased (https://github.com/open-telemetry/opentelemetry-specification/pull/611)
ParentOrElse renamed to ParentBased (https://github.com/open-telemetry/opentelemetry-specification/pull/610)
OTLP exporter unified configuration for Tracing/Metrics (https://github.com/open-telemetry/opentelemetry-specification/pull/820)
Add Translation of InstrumentationLibraryInfo to Jaeger/Zipkin

Success criteria - renaming these parts of the codebase where applicable

### PR DESCRIPTION
**Pull request by prondubuisi**
fixes #174
references https://github.com/open-telemetry/opentelemetry-specification/pull/611

### CODE REVIEW

**Review by beniamin — APPROVED** [review]

**Comment by beniamin** [comment]
Should be ready to merge after you sign with CLA.

**Comment by prondubuisi** [comment]
> Should be ready to merge after you sign with CLA.

Hello @beniamin I am not seeing any prompt to do the signing as was the case in my first PR, would signing this using `git commit -S -m` work?

**Comment by beniamin** [comment]
I think all you need to do is to force a new commit, I saw that in your previous PR the CLA check has passed. Maybe now it's just stucked in "waiting for stauts to be reported."

**Comment by prondubuisi** [comment]
> I think all you need to do is to force a new commit, I saw that in your previous PR the CLA check has passed. Maybe now it's just stucked in "waiting for stauts to be reported."

This works. Thanks. Can you help me look into my comments here https://github.com/open-telemetry/opentelemetry-php/issues/174

**Review by bobstrecansky — APPROVED** [review]

**Pull request merged**
