### PR TITLE
Update protocol buffers

### PR DESCRIPTION
**Pull request by tidal**
Update protocol buffers to be fresh and shiny!

### CODE REVIEW

**Review by brettmc — APPROVED** [review]
Looks good to me. I took a look at the coverage drops reported by codecov, and they seemed unrelated to this PR.

**Comment by tidal** [comment]
@brettmc 
Actually it says the code coverage will increased, but that doesn't make sense either.

**Comment by brettmc** [comment]
@tidal are you happy for me to merge this now?

**Comment by tidal** [comment]
@brettmc 
;)

**Pull request merged**
